[package]
name = "loco_protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { version = "2.0", default-features = false, features = ["derive"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }