[package]
name = "common_pico"
version = "0.1.0"
edition = "2024"

[dependencies]
cyw43 = { git = "https://github.com/embassy-rs/embassy.git", rev = "9cd6c92151e4ee68bca95bfc17658e50ad2c1aca", features = ["defmt", "firmware-logs"] }
cyw43-pio = { git = "https://github.com/embassy-rs/embassy.git", rev = "9cd6c92151e4ee68bca95bfc17658e50ad2c1aca", features = ["defmt"] }
defmt = "0.3"
embassy-executor = { git = "https://github.com/embassy-rs/embassy.git", rev = "9cd6c92151e4ee68bca95bfc17658e50ad2c1aca", features = ["arch-cortex-m", "executor-thread", "executor-interrupt", "defmt"] }
embassy-net = { git = "https://github.com/embassy-rs/embassy.git", rev = "9cd6c92151e4ee68bca95bfc17658e50ad2c1aca", features = ["defmt", "tcp", "udp", "raw", "dhcpv4", "medium-ethernet", "dns"] }
embassy-rp = { git = "https://github.com/embassy-rs/embassy.git", rev = "9cd6c92151e4ee68bca95bfc17658e50ad2c1aca", features = ["defmt", "unstable-pac", "time-driver", "critical-section-impl", "rp235xa", "binary-info"] }
embassy-time = { git = "https://github.com/embassy-rs/embassy.git", rev = "9cd6c92151e4ee68bca95bfc17658e50ad2c1aca", features = ["defmt", "defmt-timestamp-uptime"] }
embassy-usb-logger = { git = "https://github.com/embassy-rs/embassy.git", rev = "9cd6c92151e4ee68bca95bfc17658e50ad2c1aca" }
log = "0.4"
rand = { version = "0.8.5", default-features = false }
static_cell = "2.1"